---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: staging-cluster-issuer
 namespace: cert-manager
spec:
 acme:
   email: franco@francoposa.io
   # We use the staging server here for testing to avoid hitting
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: staging-cluster-issuer-account-key
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik